### ISSUE TITLE
Batch loading support

### ISSUE THREAD

**Issue by bullno1** [shopgun/graphql-erlang#143]
Not an issue per se, I'm just not sure how to do batch loading in graphql-erlang.

I'm trying to use this optimization: [dataloader](https://github.com/facebook/dataloader) to batch up individual queries into a big one.

Basically, in dataloader, a call to `dataloader.load(id)` will return a promise. At the "next tick", all ids will be sent in a single batch query to save round trip time and all promises will be resolved.

While deferring is already possible in `graphql-erlang`, "joining" is not as the concept of a "next tick" doesn't make much sense in Erlang.

Is it possible to register a callback which will be called here: https://github.com/shopgun/graphql-erlang/blob/develop/src/graphql_execute.erl#L912? It can inform the batch loader to start sending.

Alternatively, is there a better way to implement batch loading?

**Comment by jlouis** [comment]
We've wanted to have dataloader-like capabilities for some time, but it is dependent on having full concurrency support in the code base (which currently needs some timeout handling code). Indeed, once that is in, the plan is to have a hook-like functionality where you can register a small function to be run (usually you will use it to send a message).

The concurrency-work is not documented yet, mostly because it is highly experimental and still subject to change. But indeed, the `defer_loop` function is the place where you want some kind of hook in order to tick and tell a data loader process to execute its batch of work.

**Comment by bullno1** [comment]
We may need this feature soon because certain nested queries with shared nodes are performing terribly.

The batch start hook should be in `Ctx` just like `error_mod`. For extensibility, I think it should be a module just like error. The key can be something like `concurrency_mod` or `batch_mod`.
`hook:begin_loop(Ctx)` should kick the data loader process and `defer_hook:end_loop(Ctx)` can do some clean up if necessary.

For actual implementation, I'm not sure what's the right thing to do. Here's what I have in mind: In https://github.com/shopgun/graphql-erlang/blob/8e75a73892a97f43e142fabf04599acebea8eb95/src/graphql_execute.erl#L92,
wrap the call `defer_loop(DeferState)` around `Hook:begin_loop(Ctx)` and `Hook:end_loop(Ctx)`. Maybe a with a `try finally` to ensure `end_loop` is always called.
I'm not sure how error in `begin_loop` and `end_loop` should be handled, probably just like `resolver_crash`.

Any inputs on this?
