### ISSUE TITLE
Resolvers should be able to return auxiliary data

### ISSUE THREAD

**Issue by gausby** [shopgun/graphql-erlang#90]
We used to be able to send auxiliary data back from a resolver like so:

`{ok, Result, [AuxiliaryData]}`

This data would show up under the `aux` field in the query result map, but this functionality seems to be lost in a recent commit. We need to:

- [ ] Make a unit test
- [ ] Implement it for the new resolver code

**Comment by jlouis** [comment]
Investigation of this problem:

When I wrote the concurrent execution code, I had a receive clause in there which picks up every clause that doesn't match the expected clauses and then throws them away. This naturally messes with the code for auxiliary data. A later patch cleaned this up.

We already have a test case which verifies that aux data works as expected.

So I'm willing to bet that this issue was a fluke which is removed in the newer versions (0.10.0+). At least, we should investigate the cause deeper if it occurs again, since the test case we have obviously doesn't hit the needed buttons in the system then.

**Comment by gausby** [comment]
I guess I have to check my assertion in the test as this should have raised an alarm…right?

**Comment by jlouis** [comment]
It seems like it is being asserted. There's an `aux` field inside the expectation in the test.
